googleapis/nodejs-error-reporting

.circleci/config.yml
This is needed to fix the problem with the system tests on
CircleCI where the file specified by
GOOGLE_APPLICATION_CREDENTIALS could not be found.
=> chore: Specify the working_directory for sys tests

js-green-licenses.json, package.json
=> chore: license check in posttest

system-test/test-install.ts, system-test/utils.ts
Previously the output of subprocesses would only be printed if
`DEBUG` was set to `true` in the `test-install.ts` file.  This
is not helpful for tests that fail on CI.
Now if tests pass then no process output is printed to the
console.  This makes it easy to see that the tests pass.
However, if a test fails, the output of processes invoked in that
test are automatically printed to the console to help determine
the cause of the error.
=> chore: install tests print output on failure

package.json
Draft release notes are at [Draft Release v0.3.0](https://github.com/googleapis/nodejs-error-reporting/releases/tag/untagged-98a8b3dbaad275078fed).
=> chore: release v0.3.0

.circleci/config.yml
This was caused by the fact that `install` (and hence `compile`)
was not called prior to publishing.  As a result, the build
directory was never created.
=> fix: fix the `build` dir missing from releases

package.json
Draft release notes are at [Draft Release v0.3.1](https://github.com/googleapis/nodejs-error-reporting/releases/edit/untagged-0aabb3f9603fe1ee043b).
=> chore: release v0.3.1

package.json
Draft release notes at [Release Notes v0.3.2](https://github.com/googleapis/nodejs-error-reporting/releases/tag/untagged-279503e52e155db0f9bc).
=> chore: release v0.3.2

test/test-servers/koa_scaffold_server.ts
=> chore: update koa server to use `Date.now()`

package-lock.json, samples/package-lock.json
#118 caused typescript compilation failures in samples tests for some reason. Just verified locally than one more lock files update fixes that.
=> chore: update package locks

.circleci/config.yml
To allow linting samples for versions that are not released yet, we first need to `npm link`, then `npm install` in samples.
=> chore: link before install in samples

.circleci/config.yml
So basically, to make it work with versions not released yet (like 0.5.0 in this case), we need to run `npm link` both in lint and in samples test. Sad but true, don't know how to make it easier.
=> chore: fix samples linting

package-lock.json, samples/package-lock.json
- Drop support for Node v4.x.x
- Add support for Node v10.x.x
- Update dependency versions
=> chore: bump version to 0.5.0

package-lock.json, package.json
[release notes](https://github.com/googleapis/nodejs-error-reporting/releases/edit/untagged-1fac027688319935e795#)
---
This release picks up an updated dependency for [`@google-cloud/common`](https://npmjs.com/@google-cloud/common) to fix typescript compile issue for some users (e.g. #155).
* 002cf33 chore(release): bump version to 0.5.1
* 8053a41 fix: upgrade to @google-cloud/common@0.20.3 (#158)
* cc95f61 chore(deps): lock file maintenance (#157)
* 924470a chore(deps): lock file maintenance (#156)
* a631877 chore(deps): update dependency nyc to v12 (#152)
* 0aa1e97 chore(deps): update dependency sinon to v6 (#153)
* b017ad6 fix(deps): update dependency yargs to v12 (#154)
* b65a182 chore(deps): update dependency sinon to v5.1.1 (#151)
=> chore(release): bump version to 0.5.1

system-test/error-reporting.ts
These tests could not pass because they expected gcloud default
credentials to be available (typically on a developer machine). They
could not pass in the CI.
=> test: fix system tests

package-lock.json, src/configuration.ts
The inclusion of `console-log-level` broke the installation tests
by requiring TypeScript users of the error reporting library to
install `@types/console-log-level` to compile their code.
=> fix: fix installation tests

src/configuration.ts, src/logger.ts, src/populate-error-message.ts, src/request-extractors/hapi.ts, src/request-extractors/manual.ts, test/test-servers/express_scaffold_server.ts, test/unit/interfaces/hapi.ts
The previous use of `lodash.has` caused the installation tests
to fail.
=> chore: fix `lodash.has` usage

system-test/test-install.ts, tsconfig.json
Targeting `es5` caused the koa plugin, which is a generator
function, to be transpiled into a regular function.  As a result,
Koa@1 would refuse to use the plugin.
=> chore: do not target `es5`

system-test/error-reporting.ts
The failed tests can be viewed at [https://circleci.com/gh/googleapis/nodejs-error-reporting/4582?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link](https://circleci.com/gh/googleapis/nodejs-error-reporting/4582?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).
In particular, the `count` property on a error is of type `string` but was compared against a number.
=> chore: fix sys test failure caused by a type error

package.json, samples/package.json, system-test/error-reporting.ts, utils/errors-api-transport.ts
The system tests have been updated to use async/await.  This is
done to make it easier to see errors in the tests and fix them.
Fixes: #213
=> fix: sys tests use async/await to allow a fix

system-test/error-reporting.ts, utils/errors-api-transport.ts
This is being done to address the system test flakiness by having
the most recently created error item listed first in the list
of error items retrieved from the error reporting service.
=> chore: change sort order for retrieving err items

package.json
The test config was only running tests that were in directories
within the `test/unit` directory.  Now those tests as well as
test files in the `test/unit` directory itself are run.
=> chore: fix test config to include skipped tests

system-test/error-reporting.ts
This change is made to address the error:
```
Error: Quota exceeded for quota metric
'clouderrorreporting.googleapis.com/manage_error_events_data_requests'
and limit 'ManageErrorEventsDataRequestsPerMinutePerUser' of
service 'clouderrorreporting.googleapis.com'
```
=> chore: increase the system test delay

src/configuration.ts, src/google-apis/auth-client.ts, src/index.ts, system-test/error-reporting.ts, test/unit/configuration.ts, test/unit/google-apis/auth-client.ts
Adds the `reportMode` configuration option.  The
`ignoreEnvironmentCheck` configuration option is now
deprecated, and the `reportMode` option should be used
instead.
In particular, the `reportMode` can have one of three values:
* 'production' (default)
- Only report errors if NODE_ENV is set to "production".:
* 'always'
- Always report errors regardless of the value of NODE_ENV.
* 'never'
- Never report errors regardless of the value of NODE_ENV.
Fixes #127
=> feat: add a new `reportMode` configuration option

CHANGELOG.md, package.json, samples/package.json
This pull request was generated using releasetool.
=> Release @google-cloud/error-reporting v0.6.0

src/interfaces/manual.ts, test/unit/interfaces/manual.ts
Fixes: https://github.com/googleapis/nodejs-error-reporting/issues/35
I'm debating if this is semver major for typescript users.
=> refactor: cleanup types for reportManualError

src/request-extractors/hapi.ts, test/unit/request-extractors/hapi.ts
request.url can be a url.URL object.
Fixes: https://github.com/googleapis/nodejs-error-reporting/issues/196
=> fix: properly handle hapi v16+ req.url

src/interfaces/koa.ts
=> fix: in Koa2 interface await `next` as a function

CHANGELOG.md, package.json, samples/package.json
This pull request was generated using releasetool.
=> Release @google-cloud/error-reporting v0.6.2

src/index.ts, src/interfaces/koa2.ts
PR #336 fixed the Koa plugin, but didn't fix the Koa2 plugin.
Fixes: #335
=> fix: update Koa2 plugin to await next

CHANGELOG.md, package.json, samples/package.json
This pull request was generated using releasetool.
=> Release @google-cloud/error-reporting v0.6.3
